owner: sevillanitto
repo: dilo-status
i18n:
  header: Estado de Dilo
sites:
  - name: Dilo App
    url: https://diloapp.net
  - name: Dilo Web
    url: https://diloapp.net
status-website:
  cname: status.diloapp.net
  name: Estado de Dilo
