owner: sevillanitto
repo: dilo-status
i18n:
  header: Estado de Dilo
sites:
  - name: App Dilo
    url: https://app.diloapp.net
  - name: Web Dilo
    url: https://diloapp.net
  - name: API
    url: https://diloapp.net/api/supabase
status-website:
  cname: status.diloapp.net
  name: Estado de Dilo
